# Generated by Django 2.1 on 2018-08-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_data',
            field=models.FileField(upload_to=''),
        ),
    ]
