# Generated by Django 2.1 on 2018-08-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180813_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.URLField(default='https://i.ytimg.com/vi/o_j0tc0njUY/maxresdefault.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
